apiVersion: v1
kind: Pod

metadata:
 name: nginx-pod
 namespace: test

spec:
 containers:
 - name: nginx-cont
   image: nginx
   ports:
   - containerPort: 80
   - containerPort: 443

 - name: nginx-cont2
   image: nginx

 - name: nginx-cont3
   image: nginx
